//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheExpanseRPG.Core.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ModelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheExpanseRPG.Core.Model.ModelResources", typeof(ModelResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\Characters\.
        /// </summary>
        internal static string CharacterSavePath {
            get {
                return ResourceManager.GetString("CharacterSavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard, usually physical, labor and precarious employment tend to rule the lives of lower class characters. Still, that work is often all that separates them from becoming outsiders, so they cling to it. Lower class characters often depend on family and friends to help keep them out of utter poverty. They might live in failing industrial areas, inner city slums, or hardscrabble farms. In all cases, they make do with what is available and find ways to stretch out resources until the next payday or job comes al [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DescriptionLowerClass {
            get {
                return ResourceManager.GetString("DescriptionLowerClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A measure of comfort and security comes with the middle class. A steady job, often skilled labor or “white collar,” supplies the means to afford a few luxuries or non-essentials. Middle class characters might start off as a bit insular. They often separate themselves from the struggles of the lower social classes, focusing on the climb towards upper class status. Sometimes that climb leads to a slip. They tumble down to the lower class or even become outsiders. Some settle for stability instead, and prefer  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DescriptionMiddleClass {
            get {
                return ResourceManager.GetString("DescriptionMiddleClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were born and raised in the Black, on a station or ship, and have lived most, if not all, of your life out in the Belt or beyond. Separated from death by nothing more than basic support systems your whole life, you have learned to be cautious and aware of your environment.
        ///
        ///• Your native gravity is microgravity. Belters are most comfortable “on the float” and handle moving in free-fall easily. You automatically have the Dexterity (Free-fall) focus. Conversely, Earth-normal gravity is crushingly heavy  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DescriptionOriginBelt {
            get {
                return ResourceManager.GetString("DescriptionOriginBelt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With a population of some 30 billion, many Earthers are unemployed and live on government-provided Basic Assistance (generally known as just “Basic”) which provides for their essential food, housing, and medical needs, but little else. You are likely one of the few to leave Earth to find a new life elsewhere.
        ///
        ///• Your native gravity is normal gravity—“Earth-normal” or 1 g. Earthers can and do learn to operate in lower gravity, but lack the instincts of people raised in it.
        ///
        ///• Earthers have greater muscle [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DescriptionOriginEarth {
            get {
                return ResourceManager.GetString("DescriptionOriginEarth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Born in the Martian Congressional Republic, your life has been influenced by the Martian dream: to terraform the Red Planet into a lush and life-sustaining garden. Like the generations before you, you know that you will likely never see the completion of this work in your lifetime.
        ///
        ///• Your native gravity is low, the gravity of Mars rather than Earth. Martians are more comfortable with microgravity than Earthers, and better able to tolerate a full 1 g than Belters, operating in-between..
        /// </summary>
        internal static string DescriptionOriginMars {
            get {
                return ResourceManager.GetString("DescriptionOriginMars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More of a non-social class, outsiders tend to be outcasts, criminals, or non-conformists who can’t or won’t live according to society’s customs. They often lack access to things other people take for granted and learn to get by on their own, some times forming their own support networks and structures outside of those of mainstream society. Some outsiders reject the mainstream by choice, but in many cases, outsiders are pushed out by society’s biases..
        /// </summary>
        internal static string DescriptionOutsiderClass {
            get {
                return ResourceManager.GetString("DescriptionOutsiderClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper class characters sit at a society’s summit where they rarely need to worry about resources, except, of course, when they want more. Their concerns are often focused on the responsibilities and privileges associated with their status. Some are born into upper class privilege, inheriting wealth and opportunity, while others worked their way up to join the elite. In some societies, it’s almost impossible to work your way to upper class status, and even if you do, you might get less respect compared to he [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DescriptionUpperClass {
            get {
                return ResourceManager.GetString("DescriptionUpperClass", resourceCulture);
            }
        }
    }
}
